# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(upload_to='/static/img/')),
                ('url', models.URLField(blank=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='HairMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('price', models.PositiveIntegerField(verbose_name='ценв')),
                ('image', models.ImageField(blank=True, upload_to='/static/img')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('hairmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fish.HairMaster')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            bases=('fish.hairmaster',),
        ),
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('hairmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fish.HairMaster')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            bases=('fish.hairmaster',),
        ),
        migrations.CreateModel(
            name='Hairdress',
            fields=[
                ('hairmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fish.HairMaster')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            bases=('fish.hairmaster',),
        ),
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('hairmaster_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fish.HairMaster')),
                ('amount', models.PositiveIntegerField(verbose_name='количество')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            bases=('fish.hairmaster',),
        ),
        migrations.AddField(
            model_name='hairmaster',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.Category'),
        ),
    ]
